# Generated by Django 4.1.4 on 2022-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='selected',
            name='name',
            field=models.CharField(default='hey', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selected',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='selected',
            name='qnt',
            field=models.IntegerField(default=0),
        ),
    ]
