# Generated by Django 4.1.4 on 2022-12-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_soles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Soles',
            new_name='Sales',
        ),
    ]
