# Generated by Django 4.1.4 on 2022-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_soles_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
